### ISSUE TITLE
Default tag #steepshot is not added?

### ISSUE THREAD

**Issue by RenaudGagne** [Chainers/steepshot-issues#2]
As I was posting with steepshot, I then went to look for #steepshot tag and couldn't see my posts in there. So you've decided not to have steepshot as your basic tag?

**Comment by RenaudGagne** [comment]
My device is a LG G5

**Comment by pmartynov** [comment]
Related to a bug in piston. Fixed locally and created PR in piston-lib repo.

https://github.com/xeroc/piston-lib/pull/43
